[tool.bumpversion]
current_version = "1.15.26"
allow_dirty = true

[[tool.bumpversion.files]]
filename = "./changelog.md"
search = "[{current_version} (unreleased)]("
replace = "[{new_version} (unreleased)]("